./minishell -c ""
echo "Empty string exit code: $? (Expected 0)"
./minishell -c "''"
echo "'' exit code: $? (Expected 127)"
./minishell -c '""'
echo "\"\" exit code: $? (Expected 127)"
./minishell -c "."
echo ". exit code: $? (Expected 2 or 126/127? Bash gives 2)"
./minishell -c ".."
echo ".. exit code: $? (Expected 127 or 126?)"
