./minishell -c ">echo>"
echo "'>echo>' exit code: $? (Expected 2)"
./minishell -c "echo > <"
echo "'echo > <' exit code: $? (Expected 2)"
./minishell -c "()"
echo "'()' exit code: $? (Expected 2)"
./minishell -c "( )"
echo "'( )' exit code: $? (Expected 2)"
./minishell -c '"."'
echo "'\".\"' exit code: $? (Expected 127)"
