#!/usr/bin/env python3
"""
scripts/move_typedefs_to_defines.py

Scan the specified headers and collect `typedef struct` declarations
(both full definitions and forward typedefs) that have a struct tag and
produce forward declarations in `includes/defines.h`.

Rules:
- Only `typedef struct <tag> { ... } <alias>;` or `typedef struct <tag> <alias>;` are considered.
- Exclude any typedef where the tag or alias contains `_ctx`, `_args`, or `_val`.
- Enums are ignored.
- Output is grouped by source filename and typedef names are sorted alphabetically.

Usage:
  python3 scripts/move_typedefs_to_defines.py [--dry-run]

This script writes `includes/defines.h` (overwriting) unless `--dry-run` is used.
"""

from pathlib import Path
import re
import argparse
import sys
import shutil
import tempfile
from datetime import datetime

# Files to scan (user-provided list)
HEADER_LIST = [
    "includes/core.h",
    "includes/debug.h",
    "includes/gui.h",
    "includes/maths.h",
    "includes/objects.h",
    "includes/parser.h",
    "includes/physics.h",
    "includes/profiler.h",
    "includes/raytracing.h",
    "includes/editor.h",
    "includes/scene.h",
    "includes/stb.h",
    "includes/surface.h",
    "includes/utils.h",
]

GUARD = "DEFINES_H"

# Regex: match 'typedef struct <tag> { ... } alias;' or 'typedef struct <tag> alias;'
RE_TYPEDEF_STRUCT = re.compile(
    r"typedef\s+struct\s+(?P<tag>[A-Za-z_]\w*)\s*(?:\{.*?\})?\s*(?P<alias>[A-Za-z_]\w*)\s*;",
    re.DOTALL,
)

# Comments removal
RE_CCOMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
RE_LINE_COMMENT = re.compile(r"//.*?$", re.MULTILINE)


def strip_comments(text: str) -> str:
    text = RE_CCOMMENT.sub("", text)
    text = RE_LINE_COMMENT.sub("", text)
    return text


def scan_file(path: Path):
    try:
        txt = path.read_text(encoding="utf-8")
    except Exception:
        return []
    txt = txt.replace("\r\n", "\n").replace("\r", "\n")
    txt = strip_comments(txt)
    results = []
    for m in RE_TYPEDEF_STRUCT.finditer(txt):
        tag = m.group("tag")
        alias = m.group("alias")
        if not tag or not alias:
            continue
        key = (tag, alias)
        # Exclude based on common context/arg/val/param patterns (case-insensitive)
        low_tag = tag.lower()
        low_alias = alias.lower()
        EXCLUDE_SUBSTRS = ("_crx", "_ctx", "_args", "_val", "_param", "_args")
        if any(sub in low_tag for sub in EXCLUDE_SUBSTRS) or any(sub in low_alias for sub in EXCLUDE_SUBSTRS):
            continue
        results.append(key)
    return results


def build_defines(groups: dict) -> str:
    lines = []
    lines.append("/* THIS FILE IS AUTO-GENERATED by scripts/move_typedefs_to_defines.py */")
    lines.append("/* Forward declarations only; do not add full definitions here. */")
    lines.append("")
    lines.append(f"#ifndef {GUARD}")
    lines.append(f"#define {GUARD}")
    lines.append("")
    for src in sorted(groups.keys()):
        entries = groups[src]
        if not entries:
            continue
        lines.append(f"/* **** from {src} ***** */")
        for alias, tag in sorted(entries, key=lambda x: x[0]):
            lines.append(f"typedef struct {tag} {alias};")
        lines.append("")
    lines.append(f"#endif /* {GUARD} */")
    lines.append("")
    return "\n".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--dry-run", action="store_true", help="print output instead of writing file")
    g.add_argument("--apply", action="store_true", help="apply in-place typedef->struct replacements (creates backups)")
    args = ap.parse_args(argv)

    repo_root = Path(__file__).resolve().parent.parent
    groups = {}
    for rel in HEADER_LIST:
        p = (repo_root / rel).resolve()
        display = rel
        groups[display] = set()
        if not p.exists():
            # missing file — skip but keep empty group
            continue
        found = scan_file(p)
        for tag, alias in found:
            groups[display].add((alias, tag))

    out_text = build_defines(groups)
    out_path = repo_root / "includes" / "defines.h"
    if args.dry_run:
        print(out_text)
        return 0

    # write atomically to includes/defines.h
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", delete=False, encoding="utf-8", dir=str(out_path.parent)) as tf:
        tf.write(out_text)
        tmp_name = tf.name
    tmp_path = Path(tmp_name)
    tmp_path.replace(out_path)
    print(f"Wrote {out_path}")

    if not args.apply:
        return 0

    # Build eligible set of (tag, alias) pairs
    eligible = set()
    for src, items in groups.items():
        for alias, tag in items:
            eligible.add((tag, alias))

    # Regex to find typedef struct with a body
    RE_TYPEDEF_BODY = re.compile(
        r"typedef\s+struct\s+(?P<tag>[A-Za-z_]\w*)\s*\{(?P<body>.*?)\}\s*(?P<alias>[A-Za-z_]\w*)\s*;",
        re.DOTALL,
    )
    # Regex to find forward typedefs without body
    RE_TYPEDEF_FORWARD = re.compile(
        r"typedef\s+struct\s+(?P<tag>[A-Za-z_]\w*)\s*(?P<alias>[A-Za-z_]\w*)\s*;",
        re.DOTALL,
    )

    modified_summary = {}
    for rel in HEADER_LIST:
        if rel == "includes/defines.h":
            continue
        path = (repo_root / rel).resolve()
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")

        counter = {"n": 0, "f": 0}

        def _repl(m):
            tag = m.group("tag")
            alias = m.group("alias")
            if (tag, alias) in eligible:
                counter["n"] += 1
                body = m.group("body")
                return f"struct {tag} {{{body}}};"
            return m.group(0)

        # first replace typedefs with bodies -> struct tag { ... };
        new_text = RE_TYPEDEF_BODY.sub(_repl, text)

        # then remove forward-only typedefs that are eligible
        def _repl_forward(m):
            tag = m.group("tag")
            alias = m.group("alias")
            if (tag, alias) in eligible:
                counter["f"] += 1
                return ""
            return m.group(0)

        new_text2 = RE_TYPEDEF_FORWARD.sub(_repl_forward, new_text)

        if counter["n"] > 0 or counter["f"] > 0:
            # create backup
            bak = path.with_name(path.name + ".bak")
            if bak.exists():
                stamp = datetime.now().strftime("%Y%m%d%H%M%S")
                bak = path.with_name(path.name + ".bak." + stamp)
            shutil.copy2(path, bak)
            # write atomically
            with tempfile.NamedTemporaryFile("w", delete=False, encoding="utf-8", dir=str(path.parent)) as tf:
                tf.write(new_text2)
                tmpname = tf.name
            Path(tmpname).replace(path)
            modified_summary[str(rel)] = counter["n"] + counter["f"]

    # Print summary
    if modified_summary:
        print("Applied in-place replacements:")
        for f, n in modified_summary.items():
            print(f" - {f}: {n} replacements (backup: {Path(f).name}.bak)")
    else:
        print("No in-place replacements performed.")

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
